### ISSUE TITLE
Consider adding API docs to the "integrations" tab

### ISSUE THREAD

**Issue by bradford-hamilton** [cipherbin/cipher-bin-client#2]
@dviramontes I'd love your thoughts here. I was thinking with the integrations tab coming soon, should we also add API docs for posting/getting messages? This could either go in the `integrations` tab or a new `docs` type tab.

**thread:**

**Comment by dviramontes** [comment]
> @dviramontes I'd love your thoughts here. I was thinking with the integrations tab coming soon, should we also add API docs for posting/getting messages? This could either go in the `integrations` tab or a new `docs` type tab.
> 
> **thread:**

I like it! - `/docs` would be my vote!

**Comment by bradford-hamilton** [comment]
Awesome, well then we can plan to do this as well!
